README.adoc
=> fix url and no_copy issues

README.adoc
Fixes #12
URL block should not be marked as json
=> Fix styling for URL block

README.adoc
Most of the changes here are just me warping the text at 100 characters for better readability in editors.
To see the relevant changes only: go to "Files changed" tab and switch to "Display the rich diff":
Fixes #17
=> Clarified the need for the SystemApplication class and its parent class

finish/src/main/liberty/config/server.xml
Change server description in finished server.xml to be consistent with the start server.xml
=> Minor change to make the delta between start and finish server.xml cleaner

README.adoc
Removed the getting started tag.
=> Remove getting started tag from README

start/src/main/webapp/WEB-INF/web.xml, start/src/main/webapp/index.html
Add missing `webapp` and `test` directories to the start folder.
=> Add missing directories to start

finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java, finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java
Organize imports and remove unused ones
=> Minor cleanup

README.adoc
Updating readme to fix https://github.com/OpenLiberty/guide-rest-intro/issues/44
=> Updating outdated line in readme

README.adoc, finish/pom.xml
The POM had been updated and README was now referencing the wrong lines.
Changed all the references from line numbers to tags.
=> Change pom.xml references to use tags instead of line numbers

README.adoc
Addressing: https://github.com/OpenLiberty/guide-rest-intro/issues/55
=> Removing mentions of specific technologies

README.adoc
=> Merge qa to master: update readme for #55

.travis.yml
https://github.com/OpenLiberty/guides-common/issues/277
=> Forced Trusty (#74)

.gitignore, README.adoc, finish/pom.xml, finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java, finish/src/main/liberty/config/server.xml, finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java
Also use JSON-B instead of JSON-P
=> Update guide to be RESTful

.gitignore, .travis.yml, README.adoc, finish/pom.xml, finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java, finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java, finish/src/main/liberty/config/server.xml, finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java, start/pom.xml, start/src/main/liberty/config/server.xml
- #78 (Use jsonb)
- #79 (remove to force trusty)
=> Qa to Master: Use jonsb and delete force trusty

.travis.yml
=> Merge qa to master: add tag 'Jakarta EE'

.travis.yml, README.adoc, finish/pom.xml, finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java, finish/src/main/liberty/config/bootstrap.properties, finish/src/main/liberty/config/server.xml, finish/src/test/java/it/io/openliberty/guides/rest/EndpointIT.java, finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java, scripts/travisTest.sh, start/pom.xml, start/src/main/liberty/config/bootstrap.properties, start/src/main/liberty/config/server.xml
=> Qa devmode

README.adoc
Issue: https://github.com/OpenLiberty/guide-rest-intro/issues/94
=> Fixing dev mode wording

README.adoc
https://github.com/OpenLiberty/guide-rest-intro/pull/92#pullrequestreview-301495184
=> Update README.adoc to fix the ID comments

.travis.yml, scripts/travisTest.sh
=> Merge qa to master: Add version to the liberty-maven-plugin

.travis.yml, scripts/travisTest.sh
=> Merge qa to master: update dependencies version

finish/src/main/liberty/config/server.xml
Found by @ankitagrawa and requested fix
Issue: https://github.com/OpenLiberty/guide-rest-intro/issues/112
=> Fix spacing in server.xml

finish/pom.xml, finish/src/main/webapp/index.html, finish/src/test/java/it/io/openliberty/guides/rest/EndpointIT.java, start/pom.xml, start/src/main/webapp/index.html
- Issue: https://github.com/OpenLiberty/guides-common/issues/436
- jakarta web -> jakarta api
- specify versions at the plugin directly
- fix index.html: https://github.com/OpenLiberty/guides-common/issues/431
=> Dependencies update

README.adoc, finish/pom.xml, finish/src/main/webapp/index.html, finish/src/test/java/it/io/openliberty/guides/rest/EndpointIT.java, start/pom.xml, start/src/main/webapp/index.html
=> Merge qa to master: update dependencies

finish/pom.xml, start/pom.xml
=> Merge qa to master: remove failOnMissingWebXml

.travis.yml, finish/pom.xml, start/pom.xml
=> Merge qa to master: fix travis automation

README.adoc
Addresses: https://github.com/OpenLiberty/guide-rest-intro/issues/20
=> content update

.github/workflows/triggerConversion.yml
=> Merge qa to master: Support empty commit to trigger conversion

.github/workflows/test.yml
Issue: https://github.com/OpenLiberty/guides-common/issues/532
=> Merge qa to master: Update test.yml (#164)

README.adoc
add cloud-hosted guide instruction
=> Merge qa to master: Update README.adoc (#166)
